### ISSUE TITLE
ImageFolderDetail Page

### ISSUE THREAD

**Issue by jaegwans** [GDSC-SKHU/2023-DontWorry-SolutionChallenge#25]
## Description

- ImageFolderDetail page 개발

### Task

- [x] ImageFolderDetail page layout 구현
- [ ] ImageFolderDetail Api 구현
- [x] ImageComponent 효과 구현
